default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: messaging_app
  pool: 5
  username: user
  password: pass

development:
  <<: *default
  database: messaging_app_dev

test:
  <<: *default
  database: messaging_app_test

production:
  <<: *default
